- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].* swap .*)$'
    replace: '# \1'

- name: Update apt cache
  apt:
    update_cache: yes
